=== HarsanyiBalazs/XMLSchema-alapu-grafikus-szerkeszto/urlap/digitallibrary.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <xs:element name="DigitalLibrary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="BookName" type="xs:string"></xs:element>
                            <xs:element name="Author" type="xs:string"></xs:element>
                            <xs:element name="ReleaseDate" type="xs:date"></xs:element>
                            <xs:element name="FileFormats" type="formatListType"></xs:element>
                            <xs:element name="Price" type="priceListType"></xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="priceListType">
        <xs:list itemType="priceUnionType"/>
    </xs:simpleType>

    <xs:simpleType name="priceUnionType">
        <xs:union memberTypes="hufType eurType zlotyType"/>
    </xs:simpleType>

    <xs:simpleType name="hufType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9]([0-9]{2,4})HUF" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="eurType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1,2}\.[0-9]{2}EUR" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="zlotyType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1,3}\.[0-9]{2}ZLOTY" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="formatListType">
        <xs:list itemType="formatType"/>
    </xs:simpleType>

    <xs:simpleType name="formatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="pdf"/>
            <xs:enumeration value="epub"/>
            <xs:enumeration value="mobi"/>
            <xs:enumeration value="mp3"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== HarsanyiBalazs/XMLSchema-alapu-grafikus-szerkeszto/xmlpeldak/digitallibrary.xml
<?xml version="1.0" encoding="utf-8"?>

<DigitalLibrary xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="digitallibrary.xsd">
    <Book>
        <Author>JK. Rowling</Author>
        <BookName>Harry Potter</BookName>
        <ReleaseDate>2000-10-10</ReleaseDate>
        <FileFormats>pdf epub mobi</FileFormats>
        <Price>500HUF 3.00ZLOTY 2.55EUR</Price>
    </Book>
    <Book>
        <Author>J. R. R. Tolkien</Author>
        <BookName>The Hobbit</BookName>
        <ReleaseDate>1937-09-21</ReleaseDate>
        <FileFormats>pdf epub mobi mp3</FileFormats>
        <Price>2300HUF 31.00ZLOTY 11.00EUR</Price>
    </Book>
    <Book>
        <Author>Miguel de Cervantes</Author>
        <BookName>Don Quixote</BookName>
        <ReleaseDate>1605-11-24</ReleaseDate>
        <FileFormats>epub mobi</FileFormats>
        <Price>2000HUF 8.15ZLOTY 7.00EUR</Price>
    </Book>
</DigitalLibrary>
