=== HarsanyiBalazs/XMLSchema-alapu-grafikus-szerkeszto/urlap/restaurantmenu.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="menu">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" >
                                <xs:annotation>
                                    <xs:documentation>First letter is in uppercase</xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="([A-Z]){1}(.)+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="price">
                                <xs:annotation>
                                    <xs:documentation>Minimum 1000 and is in HUF</xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:positiveInteger">
                                        <xs:minInclusive value="1000"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="available">
                                <xs:annotation>
                                    <xs:appinfo>type="radio"</xs:appinfo>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Yes"></xs:enumeration>
                                        <xs:enumeration value="No"></xs:enumeration>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== HarsanyiBalazs/XMLSchema-alapu-grafikus-szerkeszto/xmlpeldak/restaurantmenu.xml
<?xml version="1.0" encoding="utf-8"?>

<menu xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="restaurantmenu.xsd">
    <item>
        <name>Spaghetti</name>
        <price>3200</price>
        <available>Yes</available>
    </item>
    <item>
        <name>Tomato soup</name>
        <price>2100</price>
        <available>Yes</available>
    </item>
    <item>
        <name>Pizza</name>
        <price>5000</price>
        <available>No</available>
    </item>
</menu>
