=== HarsanyiBalazs/XMLSchema-alapu-grafikus-szerkeszto/xmlpeldak/vallalat.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- A gyokerelem elemei  -->

    <xs:element name="Vallalat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Dolgozo" type="dolgozoTipus" maxOccurs="unbounded"/>
                <xs:element name="Beosztas" type="beosztasTipus" maxOccurs="unbounded"/>
                <xs:element name="Eszkoz" type="eszkozTipus" maxOccurs="unbounded"/>
                <xs:element name="Osztaly" type="osztalyTipus" maxOccurs="unbounded"/>
                <xs:element name="Osztaly-Epulet_beosztas" type="osztaly-epulet_beosztasTipus" maxOccurs="unbounded"/>
                <xs:element name="Epulet" type="epuletTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    


    <!--a fo kulcsok-->

        <xs:key name="dolgozo_kulcs">
            <xs:selector xpath="Dolgozo" />
            <xs:field xpath="@id" />
        </xs:key>

        <xs:key name="beosztas_kulcs">
            <xs:selector xpath="Beosztas" />
            <xs:field xpath="@BID" />
        </xs:key>

        <xs:key name="eszkoz_kulcs">
            <xs:selector xpath="eszkoz" />
            <xs:field xpath="@EID" />
        </xs:key>

        <xs:key name="osztaly_kulcs">
            <xs:selector xpath="Osztaly" />
            <xs:field xpath="@OID" />
        </xs:key>

        <xs:key name="epulet_kulcs">
            <xs:selector xpath="Epulet" />
            <xs:field xpath="@ÉID" />
        </xs:key>

        <!--az idegen kulcsok-->

        <xs:keyref refer="dolgozo_kulcs" name="eszkoz_dolgozo_idegen_kulcs">
            <xs:selector xpath="Eszkoz" />
            <xs:field xpath="@E_D" />
        </xs:keyref>

        <xs:keyref refer="osztaly_kulcs" name="dolgozo_osztaly_idegen_kulcs">
            <xs:selector xpath="Dolgozo" />
            <xs:field xpath="@D_O" />
        </xs:keyref>

        <xs:keyref refer="osztaly_kulcs" name="OE_osztaly_idegen_kulcs">
            <xs:selector xpath="Osztaly-Epulet_beosztas" />
            <xs:field xpath="@OE_O" />
        </xs:keyref>

        <xs:keyref refer="epulet_kulcs" name="OE_epulet_idegen_kulcs">
            <xs:selector xpath="Osztaly-Epulet_beosztas" />
            <xs:field xpath="@OE_E" />
        </xs:keyref>

        <!-- 1-1 kapcsolat megvalositasa-->

        <xs:unique name="unique_beosztas">
            <xs:selector xpath="Beosztas" />
            <xs:field xpath="@B_D" />
        </xs:unique>

    </xs:element>

    <!-- tipusok-->
    

    <!--a dolgozo tipus es benne levo elemek-->
    <xs:complexType name="dolgozoTipus">
        <xs:sequence>
            <xs:element ref="Fizetes" />
            <xs:element ref="Nev" />
            <xs:element name="Cim" type="cimTipus"/>
            <xs:element ref="Vegzettseg" />
            <xs:element ref="E-mail" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="D_O" type="xs:string" use="required" />
    </xs:complexType>

    <xs:element name="Fizetes" type="xs:positiveInteger" />
    <xs:element name="Nev" type="xs:string" />
    <xs:element name="Vegzettseg" type="xs:string" />
    <xs:element name="E-mail">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                 <xs:pattern value="([a-zA-Z0-9])+@([a-zA-Z0-9])+\.([a-zA-Z0-9])+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>


    <!--a cimtipus es a benne levo elemek-->
    <xs:complexType name="cimTipus">
        <xs:sequence>
            <xs:element ref="Iranyito_szam" />
            <xs:element ref="Varos" />
            <xs:element ref="Utca" />
        </xs:sequence>
    </xs:complexType>

    <!--az iranyitoszam elem csak magyar iranyitoszamokat fogad el-->
    <xs:element name="Iranyito_szam">
        <xs:simpleType>
            <xs:restriction base="xs:positiveInteger">
                <xs:minInclusive value="1000"/>
                <xs:maxInclusive value="9999"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Varos" type="xs:string" />
    <xs:element name="Utca" type="xs:string" />



    <!-- a beosztastipus es a benne levo elemek-->
    <xs:complexType name="beosztasTipus">
        <xs:sequence>
            <xs:element ref="Minimum_vegzettseg" />
            <xs:element ref="Beosztas_nev" />
        </xs:sequence>
        <xs:attribute name="BID" type="xs:string" use="required" />
        <xs:attribute name="B_D" type="xs:string" />
    </xs:complexType>
    
    <!--az minimum vegzettsegbe csak a Diploma es Érettségi ertekeket fogadja el-->
    <xs:element name="Minimum_vegzettseg" >
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Diploma"/>
                <xs:enumeration value="Érettségi"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Beosztas_nev" type="xs:string" />


    <!-- az eszkoztipus es a benne levo elemek-->
    <xs:complexType name="eszkozTipus">
        <xs:sequence>
            <xs:element ref="Eszkoz_nev" />
            <xs:element ref="Ar" />
        </xs:sequence>
        <xs:attribute name="EID" type="xs:string" use="required" />
        <xs:attribute name="E_D" type="xs:string" use="required" />
    </xs:complexType>

    <xs:element name="Eszkoz_nev" type="xs:string" />
    <xs:element name="Ar" type="xs:integer" />


    <!-- az osztalytipus es a benne levo elemek-->
    <xs:complexType name="osztalyTipus">
        <xs:sequence>
            <xs:element ref="Osztaly_nev" />
        </xs:sequence>
        <xs:attribute name="OID" type="xs:string" use="required" />
    </xs:complexType>

    <xs:element name="Osztaly_nev" type="xs:string" />


    <!-- az osztaly-epulet_beosztasTipus es a benne levo elemek-->
    <xs:complexType name="osztaly-epulet_beosztasTipus">
        <xs:sequence>
            <xs:element ref="Mikortol" />
        </xs:sequence>
        <xs:attribute name="OE_O" type="xs:string" use="required" />
        <xs:attribute name="OE_E" type="xs:string" use="required" />
    </xs:complexType>

    <xs:element name="Mikortol" type="xs:date" />



    <!-- az epuletTipus_beosztasTipus es a benne levo elemek-->
    <xs:complexType name="epuletTipus">
        <xs:sequence>
            <xs:element ref="Epulet_nev" />
            <xs:element name="Cim" type="cimTipus"/>
        </xs:sequence>
        <xs:attribute name="ÉID" type="xs:string" use="required" />
    </xs:complexType>

    <xs:element name="Epulet_nev" type="xs:string" />
    

</xs:schema>

=== HarsanyiBalazs/XMLSchema-alapu-grafikus-szerkeszto/xmlpeldak/vallalat.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- A gyokerelem nevterrel es a schema helyevel  -->

<Vallalat xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="vallalat.xsd">

    <!-- A dolgozok adatai  -->

    <Dolgozo id="d1" D_O="o1">
        <Fizetes>300000</Fizetes>
        <Nev>Lakatos Ottó</Nev>
        <Cim>  
            <Iranyito_szam>3744</Iranyito_szam>
            <Varos>Kazincbarcika</Varos>
            <Utca>Tancsics Utca 22</Utca>
        </Cim>
        <Vegzettseg>Érettségi</Vegzettseg>
        <E-mail>lakott@gmail.com</E-mail>
        <E-mail>lakO@ceges.com</E-mail>
        <E-mail>lakotthoni@freemail.com</E-mail>
    </Dolgozo>

    <Dolgozo id="d2" D_O="o2">
        <Fizetes>2000000</Fizetes>
        <Nev>Tóth Balázs</Nev>
        <Cim>  
            <Iranyito_szam>2252</Iranyito_szam>
            <Varos>Miskolc</Varos>
            <Utca>Hosok ut 1</Utca>
        </Cim>
        <Vegzettseg>Diploma</Vegzettseg>
        <E-mail>tthB@freemail.hu</E-mail>
        <E-mail>toThB@ceges.com</E-mail>
        <E-mail>tthB@yahoo.hu</E-mail>
    </Dolgozo>

    <Dolgozo id="d3" D_O="o3">
        <Fizetes>120000</Fizetes>
        <Nev>Tóth Krisztina</Nev>
        <Cim>  
            <Iranyito_szam>2252</Iranyito_szam>
            <Varos>Miskolc</Varos>
            <Utca>Hosok ut 1</Utca>
        </Cim>
        <Vegzettseg>Diploma</Vegzettseg>
        <E-mail>ttkr@freemail.hu</E-mail>
        <E-mail>toKrB@ceges.com</E-mail>
        <E-mail>ttKrB@yahoo.hu</E-mail>
    </Dolgozo>

    <!-- A beosztasok adatai  -->

    <Beosztas BID="b1" B_D="d1">
        <Minimum_vegzettseg>Érettségi</Minimum_vegzettseg>
        <Beosztas_nev>Leltár Menedzser</Beosztas_nev>
    </Beosztas>

    <Beosztas BID="b2" B_D="d2">
        <Minimum_vegzettseg>Diploma</Minimum_vegzettseg>
        <Beosztas_nev>Emberi erőforrások Menedzser</Beosztas_nev>
    </Beosztas>

    <Beosztas BID="b3" B_D="d3">
        <Minimum_vegzettseg>Diploma</Minimum_vegzettseg>
        <Beosztas_nev>Programozó</Beosztas_nev>
    </Beosztas>

    <!-- Az eszkozok adatai  -->

    <Eszkoz EID="e1" E_D="d1">
        <Eszkoz_nev>Telefon</Eszkoz_nev>
        <Ar>100000</Ar>
    </Eszkoz>

    <Eszkoz EID="e2" E_D="d2">
        <Eszkoz_nev>Laptop</Eszkoz_nev>
        <Ar>300000</Ar>
    </Eszkoz>

    <Eszkoz EID="e3" E_D="d3">
        <Eszkoz_nev>Laptop</Eszkoz_nev>
        <Ar>300000</Ar>
    </Eszkoz>

    <!-- Az osztalyok adatai  -->

    <Osztaly OID="o1">
        <Osztaly_nev>Leltár</Osztaly_nev>
    </Osztaly>

    <Osztaly OID="o2">
        <Osztaly_nev>Emberi erőforrások</Osztaly_nev>
    </Osztaly>

    <Osztaly OID="o3">
        <Osztaly_nev>Informatika</Osztaly_nev>
    </Osztaly>

    <!-- Az osztalyok és az epuletek osszekotteteseinek adatai  -->

    <Osztaly-Epulet_beosztas OE_O="o1" OE_E="ep1">
        <Mikortol>2001-12-31</Mikortol>
    </Osztaly-Epulet_beosztas>

    <Osztaly-Epulet_beosztas OE_O="o2" OE_E="ep2">
        <Mikortol>1999-04-12</Mikortol>
    </Osztaly-Epulet_beosztas>

    <Osztaly-Epulet_beosztas OE_O="o3" OE_E="ep3">
        <Mikortol>2000-08-10</Mikortol>
    </Osztaly-Epulet_beosztas>

    <!-- Az epuletek adatai  -->

    <Epulet ÉID="ep1">
        <Epulet_nev>Raktár 1</Epulet_nev>
        <Cim>  
            <Iranyito_szam>3704</Iranyito_szam>
            <Varos>Berente</Varos>
            <Utca>Berente út 5</Utca>
        </Cim>
    </Epulet>

    <Epulet ÉID="ep2">
        <Epulet_nev>Fő épület</Epulet_nev>
        <Cim>  
            <Iranyito_szam>3744</Iranyito_szam>
            <Varos>Kazincbarcika</Varos>
            <Utca>Kazinc út 5</Utca>
        </Cim>
    </Epulet>

    <Epulet ÉID="ep3">
        <Epulet_nev>Informatika épület</Epulet_nev>
        <Cim>  
            <Iranyito_szam>3744</Iranyito_szam>
            <Varos>Kazincbarcika</Varos>
            <Utca>Petőfi út 2</Utca>
        </Cim>
    </Epulet>

</Vallalat>
