=== HarsanyiBalazs/XMLSchema-alapu-grafikus-szerkeszto/xmlpeldak/vendeglatas.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="Vendeglatas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Etterem" type="etteremTipus" maxOccurs="unbounded"/>
                <xs:element name="Foszakacs" type="foszakacsTipus" maxOccurs="unbounded"/>
                <xs:element name="Szakacs" type="szakacsTipus" maxOccurs="unbounded"/>
                <xs:element name="Gyakornok" type="gyakornokTipus" maxOccurs="unbounded"/>
                <xs:element name="Vendeg" type="vendegTipus" maxOccurs="unbounded"/>
                <xs:element name="Rendeles" type="rendelesTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    

    <!--kulcsok-->

    <xs:key name="etterem_kulcs">
        <xs:selector xpath="etterem" />
        <xs:field xpath="@ekod" />
    </xs:key>

    <xs:key name="foszakacs_kulcs">
        <xs:selector xpath="foszakacs" />
        <xs:field xpath="@fkod" />
    </xs:key>

    <xs:key name="szakacs_kulcs">
        <xs:selector xpath="szakacs" />
        <xs:field xpath="@szkod" />
    </xs:key>

    <xs:key name="gyakornok_kulcs">
        <xs:selector xpath="gyakornok" />
        <xs:field xpath="@gykod" />
    </xs:key>

    <xs:key name="vendeg_kulcs">
        <xs:selector xpath="vendeg" />
        <xs:field xpath="@vkod" />
    </xs:key>



    <xs:keyref refer="etterem_kulcs" name="etterem_idegen_kulcs">
        <xs:selector xpath="rendeles" />
        <xs:field xpath="@e_v_e" />
    </xs:keyref>

    <xs:keyref refer="vendeg_kulcs" name="vendeg_idegen_kulcs">
        <xs:selector xpath="rendeles" />
        <xs:field xpath="@e_v_v" />
    </xs:keyref>

    <xs:keyref refer="etterem_kulcs" name="etterem_foszakacs_idegen_kulcs">
        <xs:selector xpath="foszakacs" />
        <xs:field xpath="@e_f" />
    </xs:keyref>

    <xs:keyref refer="etterem_kulcs" name="etterem_szakacs_idegen_kulcs">
        <xs:selector xpath="szakacs" />
        <xs:field xpath="@e_sz" />
    </xs:keyref>

    <xs:keyref refer="etterem_kulcs" name="etterem_gyakornok_idegen_kulcs">
        <xs:selector xpath="gyakornok" />
        <xs:field xpath="@e_gy" />
    </xs:keyref>

    <!-- 1:1 kapcsolat -->

    <xs:unique name="unique_foszakacs">
        <xs:selector xpath="foszakacs" />
        <xs:field xpath="@e_f" />
    </xs:unique>

    </xs:element>


    <!--komplex tipusok definialasa-->

    <xs:complexType name="etteremTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Cim" type="cimTipus"/>
            <xs:element name="Csillag" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="ekod" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="cimTipus">
        <xs:sequence>
            <xs:element name="Varos" type="xs:string"/>
            <xs:element name="Utca" type="xs:string"/>
            <xs:element name="Hazszam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="foszakacsTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Eletkor" type="xs:integer"/>
            <xs:element name="Vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="fkod" type="xs:string" use="required" />
        <xs:attribute name="e_f" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="szakacsTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Reszleg" type="xs:string"/>
            <xs:element name="Vegzettseg" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="szkod" type="xs:string" use="required" />
        <xs:attribute name="e_sz" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="gyakornokTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Gyakorlat" type="gyakorlatTipus"/>
            <xs:element name="Muszak" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="gykod" type="xs:string" use="required" />
        <xs:attribute name="e_gy" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="gyakorlatTipus">
        <xs:sequence>
            <xs:element name="Kezdete" type="xs:string"/>
            <xs:element name="Idotartama" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="vendegTipus">
        <xs:sequence>
            <xs:element name="Cim" type="cimTipus"/>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Eletkor" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="vkod" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="rendelesTipus">
        <xs:sequence>
            <xs:element name="Osszeg" type="xs:integer"/>
            <xs:element name="Etel" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="e_v_e" type="xs:string" use="required" />
        <xs:attribute name="e_v_v" type="xs:string" use="required" />
    </xs:complexType>

</xs:schema>

=== HarsanyiBalazs/XMLSchema-alapu-grafikus-szerkeszto/xmlpeldak/vendeglatas.xml
<?xml version="1.0" encoding="utf-8"?>

<Vendeglatas xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="vendeglatas.xsd">

    <Etterem ekod="e1">
        <Nev>Trofea</Nev>
        <Cim>
            <Varos>Budapest</Varos>
            <Utca>Visegradi</Utca>
            <Hazszam>13</Hazszam>
        </Cim>
        <Csillag>4</Csillag>
    </Etterem>

    <Etterem ekod="e2">
        <Nev>Grundel</Nev>
        <Cim>
            <Varos>Kazincbarcika</Varos>
            <Utca>Tancsics</Utca>
            <Hazszam>20</Hazszam>
        </Cim>
        <Csillag>3</Csillag>
    </Etterem>

    <Foszakacs fkod="f1" e_f="e1">
        <Nev>Benedek Elek</Nev>
        <Eletkor>35</Eletkor>
        <Vegzettseg>Szakkozep iskola</Vegzettseg>
        <Vegzettseg>Le Cordon Bleu</Vegzettseg>
        <Vegzettseg>Institut Paul Bocuse</Vegzettseg>
    </Foszakacs>

    <Foszakacs fkod="f2" e_f="e2">
        <Nev>Mihaly Jozsef</Nev>
        <Eletkor>32</Eletkor>
        <Vegzettseg>Foiskola</Vegzettseg>
        <Vegzettseg>Le Cordon Bleu</Vegzettseg>
    </Foszakacs>

    <Szakacs szkod="sz1" e_sz="e1">
        <Nev>Otlet Elek</Nev>
        <Reszleg>Saucer</Reszleg>
        <Vegzettseg>Szakkozep iskola</Vegzettseg>
        <Vegzettseg>Le Cordon Bleu</Vegzettseg>
    </Szakacs>

    <Szakacs szkod="sz2" e_sz="e2">
        <Nev>Haragos Antal</Nev>
        <Reszleg>Takarito</Reszleg>
        <Vegzettseg>Szakkozep iskola</Vegzettseg>
        <Vegzettseg>Le Cordon Bleu</Vegzettseg>
    </Szakacs>

    <Gyakornok gykod="gy1" e_gy="e1">
        <Nev>Bordas David</Nev>
        <Gyakorlat>
            <Kezdete>2024.10.08.</Kezdete>
            <Idotartama>2 honap</Idotartama>
        </Gyakorlat>
        <Muszak>Delelott</Muszak>
        <Muszak>Este</Muszak>
    </Gyakornok>

    <Gyakornok gykod="gy2" e_gy="e2">
        <Nev>Bordas Roland</Nev>
        <Gyakorlat>
            <Kezdete>2024.10.08.</Kezdete>
            <Idotartama>3 honap</Idotartama>
        </Gyakorlat>
        <Muszak>Delutan</Muszak>
    </Gyakornok>

    <Vendeg vkod="v1">
        <Cim>
            <Varos>Kazincbarcika</Varos>
            <Utca>Almos</Utca>
            <Hazszam>2</Hazszam>
        </Cim>
        <Nev>Orosz Jozsef</Nev>
        <Eletkor>22</Eletkor>
    </Vendeg>

    <Vendeg vkod="v2">
        <Cim>
            <Varos>Budapest</Varos>
            <Utca>Hosok</Utca>
            <Hazszam>66</Hazszam>
        </Cim>
        <Nev>Lakatos Antonia</Nev>
        <Eletkor>29</Eletkor>
    </Vendeg>

    <Rendeles e_v_e="gy1" e_v_v="v1">
        <Osszeg>5000</Osszeg>
        <Etel>Rantotthus</Etel>
    </Rendeles>

    <Rendeles e_v_e="gy2" e_v_v="v2">
        <Osszeg>7000</Osszeg>
        <Etel>Rakott krumpli</Etel>
    </Rendeles>

</Vendeglatas>
